### PR TITLE
fix horizontal scroll in mobile

### PR DESCRIPTION
**Pull request by shanmukhateja**
- add overflow-y to pre, code containers

- replace `main.scss` with `assets/css/app.scss` so we properly override `minima` theme.

> This allows code blocks to have a `background-color` to them as the theme devs intended.

### CODE REVIEW

**Comment by shanmukhateja** [comment]
Any errors on browser DevTools esp. on the Network tab (404 for app.css I suspect) and/or Console?

In my case, I fixed this by renaming `_site` to `babysteps` and then be use `python3 -m http.server` to spin up a web server.

**Comment by shanmukhateja** [comment]
Hey @nikomatsakis 

I figured out why the CSS was out of place. It turns out, `minima` theme wasn't being processed by SCSS as the gem wasn't officially in your Gemfile.

I don't know why it worked till now but I've tested this with `make serve` and it works as expected.

**Comment by nikomatsakis** [comment]
@shanmukhateja Sorry, I missed the updates here. Mysteriously, I still see the same thing when I do `make serve` though! I'm going to give it another try in a bit.

**Comment by shanmukhateja** [comment]
@nikomatsakis hey in that case, can you cherry pick the CSS changes for `pre` nad/or `code` HTML tags instead?

Once merged, you could close this PR.

**Comment by nikomatsakis** [comment]
@shanmukhateja I tried to cherry-pick your changes as I published the latest post -- did it work? :)

**Comment by nikomatsakis** [comment]
I have no idea why your other edits didn't work :(

At some point I'd like to redo this theme, and probably port over to some other system...

**Comment by shanmukhateja** [comment]
Hey @nikomatsakis 

It's still happening sorry. I still see horizontal scroll on the website esp. ones with`pre` tag.

I am all for using another theme and maybe this time you could integrate it properly 😅

**Pull request closed without merging**
